require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^# [^\n]+'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'app/models/concerns/**/*.rb'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*'

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Rails/ActionOrder:
  ExpectedOrder:
    - index
    - show
    - new
    - create
    - edit
    - update
    - destroy

Rails/DynamicFindBy:
  Enabled: false

Rails/SkipsModelValidations:
  AllowedMethods:
    - increment!
    - decrement!
    - touch

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - permissions

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/NestedGroups:
  Max: 5

RSpec/Rails/NegationBeValid:
  EnforcedStyle: be_invalid

RSpec/SortMetadata:
  Exclude:
    - spec/policies/*

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/Documentation:
  Enabled: false
